#! /bin/sh 

#
# Start/stop aesdsocket
#

DAEMON="/usr/bin/aesdsocket"
DAEMON_NAME="aesdsocket"
DAEMON_ARGS="-d"

 
case "$1" in 
      start) 
           echo "Starting $DAEMON_NAME" 
           start-stop-daemon -S -n $DAEMON_NAME -a $DAEMON -- $DAEMON_ARGS 
           RET=$?
           [ $RET -eq 0 ] && echo "$DAEMON_NAME started" || echo "$DAEMON_NAME started with issues"
           ;; 
     stop) 
           echo "Stopping $DAEMON_NAME" 
           start-stop-daemon -K -n DAEMON_NAME -s TERM 
           RET=$?
           [ $RET -eq 0 ] && echo "$DAEMON_NAME stopped" || echo "$DAEMON_NAME stopped with issue"
           ;; 
     *) 
           echo "Usage: $0 {start|stop}" 
           exit 1 
esac 
 
exit 0
